### PR TITLE
Add fallback option to link to homepage if target entry does not exist

### PR DESCRIPTION
**Pull request by niektenhoopen**
I have added a fallback option to link to the homepage of the target site if the requested entry does not exist on the target site.

### CODE REVIEW

**Comment by niektenhoopen** [comment]
@lindseydiloreto I couldn't find this feature in the current code. Feel free to shoot this PR down if I missed an already existing feature.

**Comment by niektenhoopen** [comment]
@lindseydiloreto I am not sure if this repo is still actively maintained. It has been one and half months and this PR hasn't even been noticed?

**Comment by lindseydiloreto** [comment]
Hey @niektenhoopen, sorry for the very late response! Technically, this repo is still being maintained. It is not abandoned, although it receives very little maintenance. 

However, we no longer use it on any of our projects (we have almost no multi-site projects). I may eventually try to find a responsible and trustworthy developer to take over this plugin. We are still very proud of this plugin, but we don't really use it anymore.

I'll try to take a look at your PR in the near future. Sorry again for the delay.

**Comment by niektenhoopen** [comment]
@lindseydiloreto Did you already found time? It has been 6 months and my PR adds basically one if-statement and one line of code.

**Comment by lindseydiloreto** [comment]
Hi @niektenhoopen, sorry for the significant delay.

I just reviewed everything and made a few relatively minor tweaks. It's all live now in **v2.2.0**.

Thanks for the contribution! 🍺

**Pull request merged**
